config/routes.rb
Pinteresting::Application.routes.draw do
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do
    member do 
      put "like", to: "posts#like"
      put "dislike", to: "posts#dislike"
    end
    resources :comments do
      member do 
        put "like", to: "comments#like"
        put "dislike", to: "comments#dislike"
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "posts#index"
  get "about" => "pages#about"
  get "terms_of_service" => "pages#terms_of_service"
  get "privacy_policy" => "pages#privacy_policy"
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	acts_as_taggable
	belongs_to :user
	has_many :comments

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#" }

	validates :image, presence: true
	validates :description, presence: true


	def to_param
  	"#{id} #{description}".parameterize
	end

	
	def next
	  	Post.where(["id < ?", id]).order(:id).last
		end

		def previous
		  Post.where(["id > ?", id]).order(:id).first
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    if params[:tag]
      @posts = Post.all.order("created_at DESC").tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10)
    else
      @posts = Post.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
  end


  def new
    @post = current_user.posts.build
  end

  def like
    @post = Post.find(params[:id])
    @post.liked_by current_user

    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @post.get_upvotes.size, id: params[:id] } }
    end
  end

  def dislike
    @post = Post.find(params[:id])
    @post.disliked_by current_user

    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @post.get_upvotes.size, id: params[:id] } }
    end
  end

  def edit
  end


  def create
    @post = current_user.posts.build(post_params)

    if @post.save
     redirect_to @post, notice: 'Post was successfully created.'
      
    else
     render action: 'new'
     end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% content_for :head do %>
  <title>Pixbored | Upload</title>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <div class="textarea">
    <%= f.label :Caption %>
    <%= f.text_area :description, :maxlength => 140, class: "form-control", placeholder: "Add a caption" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list, class: "form-control", placeholder: "Seperate tags by commas", autofocus: true %>
  </div>
  <br />
  <div class="form-group">
    <%= link_to 'Cancel', :back, class: "btn btn-default btn-lg" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.button class: "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% content_for :head do %>
  <title>Pixbored | Edit</title>
<% end %>

<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title edit">
			<h2>Edit Post</h2>
		</div>
		<%= image_tag @post.image.url(:original) %>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>

app/views/posts/index.html.erb
<% content_for :head do %>
  <title>Pixbored | Laugh Hard. Work Less</title>
  <meta name="description" content="Pixbored is your destination for funny pictures, gifs and more">
  <meta property="og:site_name" content="Pixbored" />
  <meta property="og:title" content="Laugh Hard. Work Less." />
  <meta property="og:description" content="Your community for funny user submitted pics, gifs and more!" />
  <meta property="og:url" content="http://www.pixbored.com" />
  <meta property="og:type" content="blog" />
  <meta property="og:image" content="https://s3.amazonaws.com/pixbored-assets/pixbored_logo_large.png" />
<% end %>

<div itemscope itemtype="http://schema.org/Blog" id="posts">
<% @posts.each do |post| %>
  <div class="box panel panel-default">
    <header>
      <% if post.description.blank? %>
      <% else %>
        <h2 itemprop= "name" style="padding-left: 12px;"><%= link_to post.description, post %></h2>
      <% end %>
      <span itemprop = "image">
        <%= link_to image_tag(post.image.url(:original)), post %>
      <span>
    </header>
    <div class="panel-body">
      <table>
        <tr>
          <td rowspan="3"><div class="round-image-50"><%= image_tag(post.user.avatar.url(:thumb)) %>
          </div></td>
          <td><p class="author" itemprop="author">
            <strong><%= post.user.name if post.user %>
              <span itemprop="dateCreated" class="timestamp"> | 
                <%= time_ago_in_words(post.created_at) %> ago
              </span>
            </strong>
          </p></td>
        </tr>
      </table>
      <% if post.user %>
        <div class="show_actions">
          <%= link_to post_path(post, anchor: 'comments' ), class: "btn btn-default btn-xs" do%>
            <span class="glyphicon glyphicon-comment" title="comments"></span>
            <%= post.comments.count %>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.liked?(post) %>
              <%= link_to dislike_post_path(post), method: :put, remote: true, data: { type: :json }, class: "btn btn-default btn-xs" do %>
                <span class="glyphicon glyphicon-heart" style="color:#d41b1b" title="likes"></span>
                  <span class="like-count" style="color:rgba(51, 51, 51, 0.68)"><%= post.get_upvotes.size %></span>
              <% end %>
            <% else %>
              <%= link_to like_post_path(post), method: :put, remote: true, data: { type: :json }, class: "btn btn-default btn-xs" do %>
                <span class="glyphicon glyphicon-heart"></span>
                  <span class="like-count"><%= post.get_upvotes.size %></span>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, notice: 'You must be logged in to do that', class: "btn btn-default btn-xs" do %>
              <span class="glyphicon glyphicon-heart"></span>
                <span class="like-count"><%= post.get_upvotes.size %></span>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if post.tags.any? %>
        <div class = "tags">
          <span class="glyphicon glyphicon-tag"></span> 
            <%= raw post.tag_list.map { |t| link_to t, tag_path(t), class: "btn btn-default btn-xs"}.join(' ') %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
</div>

<div class = "paginate">
  <%= will_paginate @posts, :page_links => false, renderer: BootstrapPagination::Rails %>    
</div>


<script>
  $(".btn")
    .on('ajax:success', function (e, data, status, xhr) { $(this).find("span.like-count").html(data.count); });
    $('.glyphicon-heart').click(function(){
        $(this).css("color","#d41b1b");
    });

  $(".btn-default").click(function(){
    $(this).css("color","rgba(51, 51, 51, 0.68)")
      $(this).find(".glyphicon-heart").css("color","#d41b1b")
  });

</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55978328-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/posts/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title">
			<h2>Upload an Image</h2>
			<p style="color:rgb(226, 226, 226)">Add your favorite pic or gif by uploading or dragging it into the box below!</p>
		</div>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>

app/views/posts/show.html.erb
<% content_for :head do %>
  <title><%= @post.description %> | Pixbored</title>
  <meta property="og:site_name" content="Pixbored" />
  <meta property="og:title" content="<%= @post.description %>" />
  <meta property="og:url" content="<%= "http://pixbored.com" + post_path(@post) %>" />
  <meta property="og:type" content="blog" />
  <meta property="og:image" content='<%= @post.image.url(:original) %>' />
<% end %>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= image_tag @post.image.url(:original) %>
      </div>
    </div>
  </div>
</div>


<div itemprop="BlogPosting" class="row">

	<div class="panel panel-default">
		<header>
			<% if @post.description.blank? %>
			<% else %>
				<h2 itemprop= "name" style="padding-left: 12px;"><%= @post.description %></h2>
			<% end %>
			<span id= "post-image" itemprop = "image" data-toggle="modal" data-target="#myModal">
				<%= image_tag @post.image.url(:original) %>
			</span>
		</header>
		<div class="panel-body">
			<table>
        <tr>
          <td rowspan="3"><div class="round-image-50"><%= image_tag(@post.user.avatar.url(:thumb)) %>
          </div></td>
          <td><p class="author" itemprop="author">
            <strong><%= @post.user.name if @post.user %>
              <span itemprop="dateCreated" class="timestamp"> | 
                <%= time_ago_in_words(@post.created_at) %> ago
              </span>
            </strong>
          </p></td>
        </tr>
      </table>
			<div class="show_actions">
				<% if @post.user == current_user %>
          <%= link_to @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default, btn-xs" do %>
            <span class="glyphicon glyphicon-trash" title="delete"></span>
          <% end %>
					<%= link_to edit_post_path(@post), class: "btn btn-default, btn-xs" do %>
            <span class="glyphicon glyphicon-edit" title="edit"></span>
          <% end %>
        <% end %>
        <%= link_to post_path(@post, anchor: 'comments' ), class: "btn btn-default btn-xs" do %>
          <span class="glyphicon glyphicon-comment" title="comments"></span>
          <%= @post.comments.count %>
        <% end %>
        <% if user_signed_in? %>
	        <% if current_user.liked?(@post) %>
		       	<%= link_to dislike_post_path(@post), method: :put, remote: true, data: { type: :json, toggle_href: like_post_path(@post), id: @post.id }, class: "btn btn-default btn-xs" do %>
		          <span class="glyphicon glyphicon-heart" style="color:#d41b1b" title="like"></span>
		            <span class="like-count" style="color:rgba(51, 51, 51, 0.68)"><%= @post.get_upvotes.size %></span>
		        <% end %>
		      <% else %>
		        <%= link_to like_post_path(@post), method: :put, remote: true, data: { type: :json, toggle_href: dislike_post_path(@post), id: @post.id }, class: "btn btn-default btn-xs" do %>
		          <span class="glyphicon glyphicon-heart"></span>
		            <span class="like-count"><%= @post.get_upvotes.size %></span>
		        <% end %>
		       <% end%>
		      <% else %>
		      	<%= link_to like_post_path(@post), method: :put, remote: true, data: { type: :json }, class: "btn btn-default btn-xs" do %>
		          <span class="glyphicon glyphicon-heart"></span>
		            <span class="like-count"><%= @post.get_upvotes.size %></span>
		        <% end %>
		      <% end %>
      </div>
			<% if @post.tags.any? %>
			<div class = "tags">
        <span class="glyphicon glyphicon-tag"></span> 
          <%= raw @post.tag_list.map { |t| link_to t, tag_path(t), class: "btn btn-default btn-xs"}. join(' ') %>
      </div>
      <% end %>
	</div>
</div>

<div class="post-navigation">
		<a href="javascript:fbshareCurrentPage()" target="_blank" alt="Share on Facebook" class="btn btn-primary btn-sm" id="facebook-share">
			<i class="fa fa-facebook"></i>
			Facebook</a>
		<div class="btn-group btn-group-sm">
			<%= link_to "Previous", @post.previous, class: "btn btn-default" if @post.previous.present? %>
			<%= link_to "Next", @post.next, class: "btn btn-default" if @post.next.present? %>
  	</div>
  </div>

<div class="comment-main">
	<div class="comment-form">
		<h5>
		  <% if @post.comments.count == 1 %> 
		  	<strong><%= @post.comments.count %> Comment</strong>
		  <% else %>
		  	<strong><%= @post.comments.count %> Comments</strong>
		  <% end %>
		  <span class = "text-muted" style = "float:right" > <% if user_signed_in? %>
		  	<strong><%= current_user.name %></strong>
		  	<% else %>
		  		<%= link_to "Sign in to comment", new_user_session_path %>
		  	<% end %>
		  </span>
		</h5>

		<%= simple_form_for [@post, Comment.new]  do |f| %>
		  <div class="field">
		    <%= f.text_area :body, class: "form-control", placeholder: "Join the discussion..." %>
		  </div>
		  <span class="file-input" >
		  		<%= f.file_field :image, class: "form-control" %>
		  	</span>
		  <div class = "form-footer">
		  	<button type="button" class="btn btn-sm btn-default">
		  		<span><i class="fa fa-picture-o fa-2x"></i></span>
		  	</button>
		  	<%= f.submit "Post Comment", class: "btn btn-danger" %>
		  </div>
		<% end %>
	</div>
	<div itemprop="UserComments" id="comments">
	  <%= render :partial => @post.comments %>
	</div>

	<% if @post.comments.count == 0 %>
		<br>
		<p class="text-muted" style="text-align:center">No comments yet. Be the first!</p>
	<% end %>
</div>


<script>
  $('.btn')
		.on('ajax:success', function (e, data, status, xhr) {  $(this).find("span.like-count").html(data.count); });
	$('.glyphicon-heart').click(function(){
        $(this).css("color","#d41b1b");
    });

	$(".btn-default").click(function(){
    $(this).css("color","rgba(51, 51, 51, 0.68)")
    $(this).find(".glyphicon-heart").css("color","#d41b1b")
  });
</script>

<script>
		$('.field').click(function(event){
      $('.form-footer').show();
    });

    $('button').click(function(event){
      $('span.file-input').toggle();
      $('.form-footer').css('padding-top','5px')
    });
</script>