config/routes.rb
Pinteresting::Application.routes.draw do
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do
    member do 
      put "like", to: "posts#like"
      put "dislike", to: "posts#dislike"
    end
    resources :comments do
      member do 
        put "like", to: "comments#like"
        put "dislike", to: "comments#dislike"
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "posts#index"
  get "about" => "pages#about"
  get "terms_of_service" => "pages#terms_of_service"
  get "privacy_policy" => "pages#privacy_policy"
  

  

end

app/views/layouts/_header.html.erb

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand"><%= link_to root_path do %>
        <div id="brand">pix<span style="color:rgb(253, 98, 98)">bored</span></div>
        <% end %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="dropdown">
            <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                <li>Topics
                <span class="caret"></span></li>
            </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <div id="tag_cloud">
                  <% tag_cloud Post.tag_counts_on(:tags).order('count desc').limit(8), %w[s m l] do |tag, css_class| %>
                    <li role="presentation"><%= link_to tag.name, tag_path(tag.name), class: css_class %></li>
                  <% end %>
                </div>
              </ul>
            </div>
          </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_post_path, class: "upload-button" do %>
                <span class="glyphicon glyphicon-picture"></span> Upload
              <% end %>
          </li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "signup-button" %></li>
        <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,900' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="mxH-Jb7SZD8hx6Ff_z8foZ_kRno17Sl1-wda2MTtRps" />
  <meta name="google-site-verification" content="bBv6WJXX7R7kogAh-NpDsLgY1nwOLdRauigPQW8H6R4" />
  <link rel="apple-touch-icon" href="ios/AppIcon.appiconset/Icon-60@2x.png" />
  <link rel="apple-touch-icon" sizes="180x180" href="ios/AppIcon.appiconset/Icon-60@3x.png" />
  <link rel="apple-touch-icon" sizes="76x76" href="ios/AppIcon.appiconset/Icon-76.png" />
  <link rel="apple-touch-icon" sizes="152x152" href="ios/AppIcon.appiconset/Icon-76@2x.png" />
  <link rel="apple-touch-icon" sizes="58x58" href="ios/AppIcon.appiconset/Icon-Small@2x.png" />
  <meta charset="UTF-8">

  <%= favicon_link_tag '/favicon.ico' %>

  <script type="text/javascript">
    if (window.location.hash && window.location.hash == '#_=_') {
        if (window.history && history.pushState) {
            window.history.pushState("", document.title, window.location.pathname);
        } else {
            // Prevent scrolling by storing the page's current scroll offset
            var scroll = {
                top: document.body.scrollTop,
                left: document.body.scrollLeft
            };
            window.location.hash = '';
            // Restore the scroll offset, should be flicker free
            document.body.scrollTop = scroll.top;
            document.body.scrollLeft = scroll.left;
        }
    }
  </script>
</head>
<body>

  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1391367397837217',
        status     : true,
        xfbml      : true,
        cookie     : true,
        version    : 'v2.2'
      });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-warning", id: "flash" ) %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

<script language="javascript">
 function fbshareCurrentPage()
 {window.open("https://www.facebook.com/sharer/sharer.php?u="+escape(window.location.href)+"&t="+document.title, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false; }
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-55978328-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
</script>